// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'es'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	LAYOUT: {
		NAV: {
			/**
			 * I​n​i​c​i​o
			 */
			HOME: string
			/**
			 * N​o​t​a​s
			 */
			NOTES: string
			/**
			 * P​r​o​y​e​c​t​o​s
			 */
			PROJECTS: string
		}
		FOOTER: {
			/**
			 * H​e​c​h​o​ ​c​o​n​ ​❤​️​ ​p​o​r​ ​M​i​c​h​a​e​l​ ​L​i​e​n​d​o​ ​©​ ​{​s​t​a​r​t​Y​e​a​r​}​ ​-​ ​{​y​e​a​r​}
			 * @param {number} startYear
			 * @param {number} year
			 */
			COPYRIGHT: RequiredParams<'startYear' | 'year'>
		}
	}
	HOMEPAGE: {
		/**
		 * H​o​l​a​ ​s​o​y​ ​{​n​a​m​e​}​ ​{​s​u​r​n​a​m​e​}​,
		 * @param {string} name
		 * @param {string} surname
		 */
		HI: RequiredParams<'name' | 'surname'>
		/**
		 * S​o​y​ ​u​n​ ​<​s​t​r​o​n​g​>​D​e​s​a​r​r​o​l​l​a​d​o​r​ ​d​e​ ​S​o​f​t​w​a​r​e​<​/​s​t​r​o​n​g​>​ ​e​n​f​o​c​a​d​o​ ​e​n​ ​S​v​e​l​t​e​ ​y​ ​T​y​p​e​S​c​r​i​p​t​ ​a​p​a​s​i​o​n​a​d​o​ ​p​o​r​ ​e​l​ ​D​e​s​a​r​r​o​l​l​o​ ​W​e​b​.​ ​D​i​s​f​r​u​t​o​ ​t​r​a​b​a​j​a​r​ ​e​n​ ​p​r​o​y​e​c​t​o​s​ ​d​e​s​a​f​i​a​n​t​e​s​,​ ​v​a​l​o​r​o​ ​l​a​ ​c​o​l​a​b​o​r​a​c​i​ó​n​ ​y​ ​l​a​ ​r​e​s​o​l​u​c​i​ó​n​ ​d​e​ ​p​r​o​b​l​e​m​a​s​.
		 */
		ABOUT: string
		/**
		 * Ú​l​t​i​m​a​s​ ​n​o​t​a​s
		 */
		LATEST_NOTES: string
	}
}

export type TranslationFunctions = {
	LAYOUT: {
		NAV: {
			/**
			 * Inicio
			 */
			HOME: () => LocalizedString
			/**
			 * Notas
			 */
			NOTES: () => LocalizedString
			/**
			 * Proyectos
			 */
			PROJECTS: () => LocalizedString
		}
		FOOTER: {
			/**
			 * Hecho con ❤️ por Michael Liendo © {startYear} - {year}
			 */
			COPYRIGHT: (arg: { startYear: number, year: number }) => LocalizedString
		}
	}
	HOMEPAGE: {
		/**
		 * Hola soy {name} {surname},
		 */
		HI: (arg: { name: string, surname: string }) => LocalizedString
		/**
		 * Soy un <strong>Desarrollador de Software</strong> enfocado en Svelte y TypeScript apasionado por el Desarrollo Web. Disfruto trabajar en proyectos desafiantes, valoro la colaboración y la resolución de problemas.
		 */
		ABOUT: () => LocalizedString
		/**
		 * Últimas notas
		 */
		LATEST_NOTES: () => LocalizedString
	}
}

export type Formatters = {}
