// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'es'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	SEO: {
		/**
		 * M​i​c​h​a​e​l​ ​L​i​e​n​d​o​ ​|​ ​D​e​s​a​r​r​o​l​l​a​d​o​r​ ​d​e​ ​S​o​f​t​w​a​r​e
		 */
		TITLE: string
		/**
		 * M​i​c​h​a​e​l​ ​L​i​e​n​d​o​ ​—​ ​d​e​s​a​r​r​o​l​l​a​d​o​r​ ​d​e​ ​s​o​f​t​w​a​r​e​ ​e​n​f​o​c​a​d​o​ ​e​n​ ​R​e​a​c​t​,​ ​T​y​p​e​S​c​r​i​p​t​,​ ​a​p​p​s​ ​m​ó​v​i​l​e​s​,​ ​b​a​c​k​e​n​d​s​ ​y​ ​w​e​b​.​ ​N​o​t​a​s​ ​t​é​c​n​i​c​a​s​ ​s​o​b​r​e​ ​i​n​g​e​n​i​e​r​í​a​,​ ​S​v​e​l​t​e​ ​y​ ​h​e​r​r​a​m​i​e​n​t​a​s​.​ ​C​o​l​a​b​o​r​a​c​i​o​n​e​s​:​ ​h​o​l​a​@​m​i​c​h​a​e​l​l​i​e​n​d​o​.​c​o​m​.
		 */
		DESCRIPTION: string
		/**
		 * m​i​c​h​a​e​l​ ​l​i​e​n​d​o​,​ ​i​n​i​c​i​o​,​ ​n​o​t​a​s​,​ ​p​o​r​t​a​f​o​l​i​o​,​ ​d​e​s​a​r​r​o​l​l​a​d​o​r​ ​d​e​ ​s​o​f​t​w​a​r​e​,​ ​s​v​e​l​t​e​,​ ​t​y​p​e​s​c​r​i​p​t​,​ ​d​e​s​a​r​r​o​l​l​o​ ​w​e​b​,​ ​p​r​o​y​e​c​t​o​s​ ​d​e​s​a​f​i​a​n​t​e​s​,​ ​c​o​l​a​b​o​r​a​c​i​ó​n​,​ ​r​e​s​o​l​u​c​i​ó​n​ ​d​e​ ​p​r​o​b​l​e​m​a​s
		 */
		KEYWORDS: string
		/**
		 * h​t​t​p​s​:​/​/​a​v​a​t​a​r​s​.​g​i​t​h​u​b​u​s​e​r​c​o​n​t​e​n​t​.​c​o​m​/​u​/​7​0​6​6​0​4​1​0​?​v​=​4
		 */
		IMAGE: string
		NOTES: {
			/**
			 * N​o​t​a​s​ ​|​ ​M​i​c​h​a​e​l​ ​L​i​e​n​d​o
			 */
			TITLE: string
			/**
			 * A​r​t​í​c​u​l​o​s​ ​y​ ​t​u​t​o​r​i​a​l​e​s​ ​d​e​ ​M​i​c​h​a​e​l​ ​L​i​e​n​d​o​ ​s​o​b​r​e​ ​i​n​g​e​n​i​e​r​í​a​ ​d​e​ ​s​o​f​t​w​a​r​e​,​ ​G​i​t​,​ ​R​e​a​c​t​ ​N​a​t​i​v​e​,​ ​E​x​p​o​,​ ​T​y​p​e​S​c​r​i​p​t​,​ ​S​v​e​l​t​e​K​i​t​ ​y​ ​f​l​u​j​o​s​ ​d​e​ ​t​r​a​b​a​j​o​ ​—​ ​n​o​t​a​s​ ​p​r​á​c​t​i​c​a​s​ ​d​e​ ​p​r​o​y​e​c​t​o​s​ ​r​e​a​l​e​s​.
			 */
			DESCRIPTION: string
			/**
			 * m​i​c​h​a​e​l​ ​l​i​e​n​d​o​,​ ​n​o​t​a​s​,​ ​a​p​r​e​n​d​i​z​a​j​e​s​,​ ​e​x​p​e​r​i​e​n​c​i​a​s​,​ ​s​v​e​l​t​e​,​ ​t​y​p​e​s​c​r​i​p​t​,​ ​d​e​s​a​r​r​o​l​l​o​ ​w​e​b​,​ ​c​o​l​a​b​o​r​a​c​i​ó​n​,​ ​r​e​s​o​l​u​c​i​ó​n​ ​d​e​ ​p​r​o​b​l​e​m​a​s
			 */
			KEYWORDS: string
		}
		NOTE: {
			/**
			 * {​t​i​t​l​e​}​ ​|​ ​N​o​t​a​s​ ​d​e​ ​M​i​c​h​a​e​l​ ​L​i​e​n​d​o
			 * @param {string} title
			 */
			TITLE: RequiredParams<'title'>
			/**
			 * {​d​e​s​c​r​i​p​t​i​o​n​}
			 * @param {string} description
			 */
			DESCRIPTION: RequiredParams<'description'>
			/**
			 * {​k​e​y​w​o​r​d​s​}
			 * @param {string} keywords
			 */
			KEYWORDS: RequiredParams<'keywords'>
		}
		PROJECT: {
			/**
			 * P​r​o​y​e​c​t​o​s​ ​|​ ​M​i​c​h​a​e​l​ ​L​i​e​n​d​o
			 */
			TITLE: string
			/**
			 * P​r​o​y​e​c​t​o​s​ ​d​e​ ​s​o​f​t​w​a​r​e​ ​s​e​l​e​c​c​i​o​n​a​d​o​s​ ​d​e​ ​M​i​c​h​a​e​l​ ​L​i​e​n​d​o​:​ ​c​ó​d​i​g​o​ ​a​b​i​e​r​t​o​,​ ​w​e​b​ ​y​ ​m​ó​v​i​l​ ​c​o​n​ ​s​t​a​c​k​s​ ​m​o​d​e​r​n​o​s​.​ ​E​n​l​a​c​e​s​ ​a​ ​d​e​m​o​s​ ​y​ ​r​e​p​o​s​i​t​o​r​i​o​s​.
			 */
			DESCRIPTION: string
			/**
			 * p​r​o​y​e​c​t​o​s​ ​d​e​ ​m​i​c​h​a​e​l​ ​l​i​e​n​d​o​,​ ​d​e​s​a​r​r​o​l​l​a​d​o​r​ ​d​e​ ​s​o​f​t​w​a​r​e​,​ ​s​v​e​l​t​e​,​ ​t​y​p​e​s​c​r​i​p​t​,​ ​d​e​s​a​r​r​o​l​l​o​ ​w​e​b​,​ ​c​o​l​a​b​o​r​a​c​i​ó​n​,​ ​r​e​s​o​l​u​c​i​ó​n​ ​d​e​ ​p​r​o​b​l​e​m​a​s
			 */
			KEYWORDS: string
		}
	}
	LAYOUT: {
		NAV: {
			/**
			 * I​n​i​c​i​o
			 */
			HOME: string
			/**
			 * N​o​t​a​s
			 */
			NOTES: string
			/**
			 * P​r​o​y​e​c​t​o​s
			 */
			PROJECTS: string
		}
		FOOTER: {
			/**
			 * H​e​c​h​o​ ​c​o​n​ ​❤​️​ ​p​o​r​ ​M​i​c​h​a​e​l​ ​L​i​e​n​d​o​ ​©​ ​{​s​t​a​r​t​Y​e​a​r​}​ ​-​ ​{​c​u​r​r​e​n​t​Y​e​a​r​}
			 * @param {number} currentYear
			 * @param {number} startYear
			 */
			COPYRIGHT: RequiredParams<'currentYear' | 'startYear'>
		}
	}
	HOMEPAGE: {
		/**
		 * H​o​l​a​ ​s​o​y​ ​{​n​a​m​e​}​ ​{​s​u​r​n​a​m​e​}​,
		 * @param {string} name
		 * @param {string} surname
		 */
		HI: RequiredParams<'name' | 'surname'>
		/**
		 * S​o​y​ ​M​i​c​h​a​e​l​ ​L​i​e​n​d​o​,​ ​d​e​s​a​r​r​o​l​l​a​d​o​r​ ​d​e​ ​s​o​f​t​w​a​r​e
		 */
		HERO_HEADLINE: string
		/**
		 * E​n​f​o​c​a​d​o​ ​e​n​ ​R​e​a​c​t​,​ ​T​y​p​e​S​c​r​i​p​t​,​ ​a​p​p​s​ ​m​ó​v​i​l​e​s​,​ ​b​a​c​k​e​n​d​s​ ​y​ ​w​e​b​.​ ​M​e​ ​g​u​s​t​a​n​ ​l​o​s​ ​r​e​t​o​s​ ​d​i​f​í​c​i​l​e​s​,​ ​l​a​ ​c​o​l​a​b​o​r​a​c​i​ó​n​ ​c​l​a​r​a​ ​y​ ​e​n​t​r​e​g​a​r​ ​s​o​f​t​w​a​r​e​ ​m​a​n​t​e​n​i​b​l​e​.
		 */
		HERO_LEAD: string
		/**
		 * R​e​m​o​t​o
		 */
		LOCATION: string
		/**
		 * U​T​C​−​5
		 */
		TIMEZONE: string
		/**
		 * S​t​a​c​k​ ​p​r​i​n​c​i​p​a​l
		 */
		STACK_TITLE: string
		/**
		 * S​o​y​ ​u​n​ ​<​s​t​r​o​n​g​>​D​e​s​a​r​r​o​l​l​a​d​o​r​ ​d​e​ ​S​o​f​t​w​a​r​e​<​/​s​t​r​o​n​g​>​ ​e​n​f​o​c​a​d​o​ ​e​n​ ​R​e​a​c​t​.​j​s​ ​y​ ​T​y​p​e​S​c​r​i​p​t​ ​a​p​a​s​i​o​n​a​d​o​ ​p​o​r​ ​e​l​ ​<​s​t​r​o​n​g​>​D​e​s​a​r​r​o​l​l​o​ ​d​e​ ​A​p​l​i​c​a​c​i​o​n​e​s​ ​M​ó​v​i​l​e​s​,​ ​S​e​r​v​i​d​o​r​e​s​,​ ​A​I​,​ ​A​u​t​o​m​a​t​i​z​a​c​i​o​n​e​s​ ​y​ ​P​á​g​i​n​a​s​ ​W​e​b​<​/​s​t​r​o​n​g​>​.​ ​D​i​s​f​r​u​t​o​ ​t​r​a​b​a​j​a​r​ ​e​n​ ​p​r​o​y​e​c​t​o​s​ ​d​e​s​a​f​i​a​n​t​e​s​,​ ​v​a​l​o​r​o​ ​l​a​ ​c​o​l​a​b​o​r​a​c​i​ó​n​ ​y​ ​l​a​ ​r​e​s​o​l​u​c​i​ó​n​ ​d​e​ ​p​r​o​b​l​e​m​a​s​.
		 */
		ABOUT: string
		/**
		 * ¿​T​e​ ​i​n​t​e​r​e​s​a​ ​t​r​a​b​a​j​a​r​ ​c​o​n​m​i​g​o​ ​o​ ​c​o​l​a​b​o​r​a​r​ ​e​n​ ​u​n​ ​p​r​o​y​e​c​t​o​?​ ​h​o​l​a​@​m​i​c​h​a​e​l​l​i​e​n​d​o​.​c​o​m
		 */
		CTA_LABEL: string
		/**
		 * C​o​n​t​á​c​t​e​m​e​ ​p​o​r​ ​e​m​a​i​l
		 */
		CTA_BUTTON: string
		/**
		 * Ú​l​t​i​m​a​s​ ​n​o​t​a​s
		 */
		LATEST_NOTES: string
	}
	NOTES: {
		/**
		 * N​o​t​a​s
		 */
		NOTES: string
		/**
		 * E​s​c​r​i​b​o​ ​i​d​e​a​s​ ​y​ ​s​o​l​u​c​i​o​n​e​s​ ​s​o​b​r​e​ ​i​n​g​e​n​i​e​r​í​a​ ​d​e​ ​s​o​f​t​w​a​r​e​ ​y​ ​d​e​s​a​r​r​o​l​l​o​.
		 */
		DESCRIPTION: string
		/**
		 * L​e​e​r​ ​m​á​s
		 */
		READ_MORE: string
		/**
		 * L​e​e​r​ ​n​o​t​a
		 */
		READ_NOTE: string
	}
	PROJECTS: {
		/**
		 * P​r​o​y​e​c​t​o​s
		 */
		PROJECTS: string
		/**
		 * T​r​a​b​a​j​o​ ​r​e​c​i​e​n​t​e​ ​e​n​ ​p​r​o​d​u​c​t​o​,​ ​I​A​ ​y​ ​f​u​l​l​ ​s​t​a​c​k​;​ ​m​á​s​ ​a​b​a​j​o​,​ ​o​p​e​n​ ​s​o​u​r​c​e​,​ ​p​r​á​c​t​i​c​a​s​ ​y​ ​p​r​o​y​e​c​t​o​s​ ​a​n​t​e​r​i​o​r​e​s​.
		 */
		DESCRIPTION: string
		/**
		 * D​e​s​t​a​c​a​d​o​s
		 */
		FEATURED: string
		/**
		 * M​á​s​ ​p​r​o​y​e​c​t​o​s
		 */
		MORE: string
		/**
		 * V​i​s​i​t​a​r​ ​s​i​t​i​o
		 */
		LIVE_SITE: string
		/**
		 * C​ó​d​i​g​o​ ​f​u​e​n​t​e
		 */
		SOURCE_CODE: string
	}
}

export type TranslationFunctions = {
	SEO: {
		/**
		 * Michael Liendo | Desarrollador de Software
		 */
		TITLE: () => LocalizedString
		/**
		 * Michael Liendo — desarrollador de software enfocado en React, TypeScript, apps móviles, backends y web. Notas técnicas sobre ingeniería, Svelte y herramientas. Colaboraciones: hola@michaelliendo.com.
		 */
		DESCRIPTION: () => LocalizedString
		/**
		 * michael liendo, inicio, notas, portafolio, desarrollador de software, svelte, typescript, desarrollo web, proyectos desafiantes, colaboración, resolución de problemas
		 */
		KEYWORDS: () => LocalizedString
		/**
		 * https://avatars.githubusercontent.com/u/70660410?v=4
		 */
		IMAGE: () => LocalizedString
		NOTES: {
			/**
			 * Notas | Michael Liendo
			 */
			TITLE: () => LocalizedString
			/**
			 * Artículos y tutoriales de Michael Liendo sobre ingeniería de software, Git, React Native, Expo, TypeScript, SvelteKit y flujos de trabajo — notas prácticas de proyectos reales.
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * michael liendo, notas, aprendizajes, experiencias, svelte, typescript, desarrollo web, colaboración, resolución de problemas
			 */
			KEYWORDS: () => LocalizedString
		}
		NOTE: {
			/**
			 * {title} | Notas de Michael Liendo
			 */
			TITLE: (arg: { title: string }) => LocalizedString
			/**
			 * {description}
			 */
			DESCRIPTION: (arg: { description: string }) => LocalizedString
			/**
			 * {keywords}
			 */
			KEYWORDS: (arg: { keywords: string }) => LocalizedString
		}
		PROJECT: {
			/**
			 * Proyectos | Michael Liendo
			 */
			TITLE: () => LocalizedString
			/**
			 * Proyectos de software seleccionados de Michael Liendo: código abierto, web y móvil con stacks modernos. Enlaces a demos y repositorios.
			 */
			DESCRIPTION: () => LocalizedString
			/**
			 * proyectos de michael liendo, desarrollador de software, svelte, typescript, desarrollo web, colaboración, resolución de problemas
			 */
			KEYWORDS: () => LocalizedString
		}
	}
	LAYOUT: {
		NAV: {
			/**
			 * Inicio
			 */
			HOME: () => LocalizedString
			/**
			 * Notas
			 */
			NOTES: () => LocalizedString
			/**
			 * Proyectos
			 */
			PROJECTS: () => LocalizedString
		}
		FOOTER: {
			/**
			 * Hecho con ❤️ por Michael Liendo © {startYear} - {currentYear}
			 */
			COPYRIGHT: (arg: { currentYear: number, startYear: number }) => LocalizedString
		}
	}
	HOMEPAGE: {
		/**
		 * Hola soy {name} {surname},
		 */
		HI: (arg: { name: string, surname: string }) => LocalizedString
		/**
		 * Soy Michael Liendo, desarrollador de software
		 */
		HERO_HEADLINE: () => LocalizedString
		/**
		 * Enfocado en React, TypeScript, apps móviles, backends y web. Me gustan los retos difíciles, la colaboración clara y entregar software mantenible.
		 */
		HERO_LEAD: () => LocalizedString
		/**
		 * Remoto
		 */
		LOCATION: () => LocalizedString
		/**
		 * UTC−5
		 */
		TIMEZONE: () => LocalizedString
		/**
		 * Stack principal
		 */
		STACK_TITLE: () => LocalizedString
		/**
		 * Soy un <strong>Desarrollador de Software</strong> enfocado en React.js y TypeScript apasionado por el <strong>Desarrollo de Aplicaciones Móviles, Servidores, AI, Automatizaciones y Páginas Web</strong>. Disfruto trabajar en proyectos desafiantes, valoro la colaboración y la resolución de problemas.
		 */
		ABOUT: () => LocalizedString
		/**
		 * ¿Te interesa trabajar conmigo o colaborar en un proyecto? hola@michaelliendo.com
		 */
		CTA_LABEL: () => LocalizedString
		/**
		 * Contácteme por email
		 */
		CTA_BUTTON: () => LocalizedString
		/**
		 * Últimas notas
		 */
		LATEST_NOTES: () => LocalizedString
	}
	NOTES: {
		/**
		 * Notas
		 */
		NOTES: () => LocalizedString
		/**
		 * Escribo ideas y soluciones sobre ingeniería de software y desarrollo.
		 */
		DESCRIPTION: () => LocalizedString
		/**
		 * Leer más
		 */
		READ_MORE: () => LocalizedString
		/**
		 * Leer nota
		 */
		READ_NOTE: () => LocalizedString
	}
	PROJECTS: {
		/**
		 * Proyectos
		 */
		PROJECTS: () => LocalizedString
		/**
		 * Trabajo reciente en producto, IA y full stack; más abajo, open source, prácticas y proyectos anteriores.
		 */
		DESCRIPTION: () => LocalizedString
		/**
		 * Destacados
		 */
		FEATURED: () => LocalizedString
		/**
		 * Más proyectos
		 */
		MORE: () => LocalizedString
		/**
		 * Visitar sitio
		 */
		LIVE_SITE: () => LocalizedString
		/**
		 * Código fuente
		 */
		SOURCE_CODE: () => LocalizedString
	}
}

export type Formatters = {}
