name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Check
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Check
        run: npm run check

  build:
    name: Build 
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Check
        run: npm run build
